# TP - Work with text data
---

## Imports

In [1]:
import pandas as pd

## Load data

In [2]:
data = pd.read_csv("authors_description.csv", header=None, names=['description'])

In [3]:
data.head()

                                         description
0  Marc Levy (born 16 October 1961) is a French n...
1  Emmanuel Carrère (born 9 December 1957) is a F...
2  Franck Thilliez (born 15 October 1973 in Annec...
3  Kenneth Martin Follett,  (born 5 June 1949) is...
4  Stephen Edwin King (born September 21, 1947) i...

## Feature extraction

### Number of words

                                          description  wordCount
0   Marc Levy (born 16 October 1961) is a French n...         10
1   Emmanuel Carrère (born 9 December 1957) is a F...         14
2   Franck Thilliez (born 15 October 1973 in Annec...         35
3   Kenneth Martin Follett,  (born 5 June 1949) is...         85
4   Stephen Edwin King (born September 21, 1947) i...        190
5   Pierre Lemaitre (born 19 April 1951 in Paris) ...        110
6        Joël Dicker (born 1985) is a Swiss novelist.          8
7   Baroness Fabienne-Claire Nothomb, better known...        128
8   Harlan Coben (born January 4, 1962) is an Amer...         65
9   Dame Agatha Mary Clarissa Christie, Lady Mallo...        427
10  David Foenkinos (born 28 October 1974) is a Fr...         57
11  Hervé Le Tellier (born 21 April 1957) is a Fre...         57
12  Arch Colson Chipp Whitehead (born November 6, ...         80
13  Michel Bussi (born (1965-04-29)29 April 1965 i...        102
14  Guillaume Musso (French pronunciation: ​[ɡijom...         14
15  Brit Bennett is an American writer based in Lo...         47
16  Bernard Werber (born 1961 in Toulouse) is a Fr...         52
17  Laurent Mauvignier (born in 1967, Tours) is a ...         10
18  Lola Lafon (born 1974) is a French writer and ...         81
19  Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...        318
20  Laure Adler (née Laure Clauzet; born 11 March ...         20
21  Alice Zeniter (born 1986) is a French novelist...         87
22  Erri De Luca (born 20 May 1950, Naples) is an ...         84
23  Émile Édouard Charles Antoine Zola (, also US:...         94
24  Carole Martinez (10 November 1966 in Créhange)...         12
25  Marie-Hélène Lafon (born 1962) is a French edu...         83

### Number of  characters

,description,wordCount,characterCount
0,Marc Levy (born 16 October 1961) is a French n...,10,54
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93
15,Brit Bennett is an American writer based in Lo...,47,268
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60
18,Lola Lafon (born 1974) is a French writer and ...,81,468
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125
21,Alice Zeniter (born 1986) is a French novelist...,87,507
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601
24,Carole Martinez (10 November 1966 in Créhange)...,12,81
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485

### Number of numerics

**Tips:** 
- Use `isdigit` function

,description,wordCount,characterCount,numericCount
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5
15,Brit Bennett is an American writer based in Lo...,47,268,8
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18

### Number of Uppercase words

,description,wordCount,characterCount,numericCount,isUppercase
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5
15,Brit Bennett is an American writer based in Lo...,47,268,8,23
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15

## Text pre-processing

### Lowercase

**Tips:** 
- Use `description` column
- Use Pandas Series functions

,description,wordCount,characterCount,numericCount,isUppercase,lowercase
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is..."
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i..."
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known..."
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer..."
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo..."
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ..."
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ..."
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ..."
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:..."
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...

### Replace Line Return (\n) by whitespace

** Tips :** Use `lowercase` column

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...,marc levy (born 16 october 1961) is a french n...
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère (born 9 december 1957) is a f...
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...,franck thilliez (born 15 october 1973 in annec...
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is...","kenneth martin follett, (born 5 june 1949) is..."
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i...","stephen edwin king (born september 21, 1947) i..."
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre (born 19 april 1951 in paris) ...
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.,joël dicker (born 1985) is a swiss novelist.
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known...","baroness fabienne-claire nothomb, better known..."
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer...","harlan coben (born january 4, 1962) is an amer..."
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo...","dame agatha mary clarissa christie, lady mallo..."
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...,david foenkinos (born 28 october 1974) is a fr...
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier (born 21 april 1957) is a fre...
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ...","arch colson chipp whitehead (born november 6, ..."
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi (born (1965-04-29)29 april 1965 i...
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso (french pronunciation: ​[ɡijom...
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...,bernard werber (born 1961 in toulouse) is a fr...
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ...","laurent mauvignier (born in 1967, tours) is a ..."
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...,lola lafon (born 1974) is a french writer and ...
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...,laure adler (née laure clauzet; born 11 march ...
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...,alice zeniter (born 1986) is a french novelist...
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ...","erri de luca (born 20 may 1950, naples) is an ..."
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:...","émile édouard charles antoine zola (, also us:..."
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...,carole martinez (10 november 1966 in créhange)...
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...,marie-hélène lafon (born 1962) is a french edu...

### Removing Punctuation & Special Characters

**Tips :** 
- Use withoutLineReturn column
- Use `regex` to keep words : `[^\w\s]` If you need to test regex, use http://regex101.com

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...,marc levy (born 16 october 1961) is a french n...,marc levy born 16 october 1961 is a french nov...
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère born 9 december 1957 is a fre...
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...,franck thilliez (born 15 october 1973 in annec...,franck thilliez born 15 october 1973 in annecy...
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is...","kenneth martin follett, (born 5 june 1949) is...",kenneth martin follett born 5 june 1949 is a ...
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i...","stephen edwin king (born september 21, 1947) i...",stephen edwin king born september 21 1947 is a...
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre born 19 april 1951 in paris is...
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.,joël dicker (born 1985) is a swiss novelist.,joël dicker born 1985 is a swiss novelist
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known...","baroness fabienne-claire nothomb, better known...",baroness fabienneclaire nothomb better known b...
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer...","harlan coben (born january 4, 1962) is an amer...",harlan coben born january 4 1962 is an america...
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo...","dame agatha mary clarissa christie, lady mallo...",dame agatha mary clarissa christie lady mallow...
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...,david foenkinos (born 28 october 1974) is a fr...,david foenkinos born 28 october 1974 is a fren...
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier born 21 april 1957 is a frenc...
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ...","arch colson chipp whitehead (born november 6, ...",arch colson chipp whitehead born november 6 19...
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi born 1965042929 april 1965 in lou...
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso french pronunciation ɡijom mys...
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...,bernard werber (born 1961 in toulouse) is a fr...,bernard werber born 1961 in toulouse is a fren...
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ...","laurent mauvignier (born in 1967, tours) is a ...",laurent mauvignier born in 1967 tours is a fre...
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...,lola lafon (born 1974) is a french writer and ...,lola lafon born 1974 is a french writer and mu...
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 ...
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...,laure adler (née laure clauzet; born 11 march ...,laure adler née laure clauzet born 11 march 19...
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...,alice zeniter (born 1986) is a french novelist...,alice zeniter born 1986 is a french novelist t...
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ...","erri de luca (born 20 may 1950, naples) is an ...",erri de luca born 20 may 1950 naples is an ita...
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:...","émile édouard charles antoine zola (, also us:...",émile édouard charles antoine zola also us f...
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...,carole martinez (10 november 1966 in créhange)...,carole martinez 10 november 1966 in créhange i...
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...,marie-hélène lafon (born 1962) is a french edu...,mariehélène lafon born 1962 is a french educat...

### Remove stopwords

In [11]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [12]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

**Tips :** Use `withoutPunctuaction` column

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction,withoutStopwords
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...,marc levy (born 16 october 1961) is a french n...,marc levy born 16 october 1961 is a french nov...,marc levy born 16 october 1961 french novelist
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère born 9 december 1957 is a fre...,emmanuel carrère born 9 december 1957 french a...
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...,franck thilliez (born 15 october 1973 in annec...,franck thilliez born 15 october 1973 in annecy...,franck thilliez born 15 october 1973 annecy fr...
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is...","kenneth martin follett, (born 5 june 1949) is...",kenneth martin follett born 5 june 1949 is a ...,kenneth martin follett born 5 june 1949 welsh ...
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i...","stephen edwin king (born september 21, 1947) i...",stephen edwin king born september 21 1947 is a...,stephen edwin king born september 21 1947 amer...
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre born 19 april 1951 in paris is...,pierre lemaitre born 19 april 1951 paris prix ...
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.,joël dicker (born 1985) is a swiss novelist.,joël dicker born 1985 is a swiss novelist,joël dicker born 1985 swiss novelist
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known...","baroness fabienne-claire nothomb, better known...",baroness fabienneclaire nothomb better known b...,baroness fabienneclaire nothomb better known p...
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer...","harlan coben (born january 4, 1962) is an amer...",harlan coben born january 4 1962 is an america...,harlan coben born january 4 1962 american writ...
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo...","dame agatha mary clarissa christie, lady mallo...",dame agatha mary clarissa christie lady mallow...,dame agatha mary clarissa christie lady mallow...
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...,david foenkinos (born 28 october 1974) is a fr...,david foenkinos born 28 october 1974 is a fren...,david foenkinos born 28 october 1974 french au...
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier born 21 april 1957 is a frenc...,hervé le tellier born 21 april 1957 french wri...
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ...","arch colson chipp whitehead (born november 6, ...",arch colson chipp whitehead born november 6 19...,arch colson chipp whitehead born november 6 19...
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi born 1965042929 april 1965 in lou...,michel bussi born 1965042929 april 1965 louvie...
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso french pronunciation ɡijom mys...,guillaume musso french pronunciation ɡijom mys...
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett american writer based los angeles...
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...,bernard werber (born 1961 in toulouse) is a fr...,bernard werber born 1961 in toulouse is a fren...,bernard werber born 1961 toulouse french scien...
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ...","laurent mauvignier (born in 1967, tours) is a ...",laurent mauvignier born in 1967 tours is a fre...,laurent mauvignier born 1967 tours french writer
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...,lola lafon (born 1974) is a french writer and ...,lola lafon born 1974 is a french writer and mu...,lola lafon born 1974 french writer musician bo...
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 ...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 n...
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...,laure adler (née laure clauzet; born 11 march ...,laure adler née laure clauzet born 11 march 19...,laure adler née laure clauzet born 11 march 19...
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...,alice zeniter (born 1986) is a french novelist...,alice zeniter born 1986 is a french novelist t...,alice zeniter born 1986 french novelist transl...
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ...","erri de luca (born 20 may 1950, naples) is an ...",erri de luca born 20 may 1950 naples is an ita...,erri de luca born 20 may 1950 naples italian n...
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:...","émile édouard charles antoine zola (, also us:...",émile édouard charles antoine zola also us f...,émile édouard charles antoine zola also us fre...
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...,carole martinez (10 november 1966 in créhange)...,carole martinez 10 november 1966 in créhange i...,carole martinez 10 november 1966 créhange fren...
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...,marie-hélène lafon (born 1962) is a french edu...,mariehélène lafon born 1962 is a french educat...,mariehélène lafon born 1962 french educator aw...

### Tokenization

In [14]:
from nltk import tokenize
tokenizer = tokenize.SpaceTokenizer()

**Tips :** Use `withoutStopwords` column

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction,withoutStopwords,tokenized
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...,marc levy (born 16 october 1961) is a french n...,marc levy born 16 october 1961 is a french nov...,marc levy born 16 october 1961 french novelist,"[marc, levy, born, 16, october, 1961, french, ..."
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère born 9 december 1957 is a fre...,emmanuel carrère born 9 december 1957 french a...,"[emmanuel, carrère, born, 9, december, 1957, f..."
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...,franck thilliez (born 15 october 1973 in annec...,franck thilliez born 15 october 1973 in annecy...,franck thilliez born 15 october 1973 annecy fr...,"[franck, thilliez, born, 15, october, 1973, an..."
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is...","kenneth martin follett, (born 5 june 1949) is...",kenneth martin follett born 5 june 1949 is a ...,kenneth martin follett born 5 june 1949 welsh ...,"[kenneth, martin, follett, born, 5, june, 1949..."
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i...","stephen edwin king (born september 21, 1947) i...",stephen edwin king born september 21 1947 is a...,stephen edwin king born september 21 1947 amer...,"[stephen, edwin, king, born, september, 21, 19..."
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre born 19 april 1951 in paris is...,pierre lemaitre born 19 april 1951 paris prix ...,"[pierre, lemaitre, born, 19, april, 1951, pari..."
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.,joël dicker (born 1985) is a swiss novelist.,joël dicker born 1985 is a swiss novelist,joël dicker born 1985 swiss novelist,"[joël, dicker, born, 1985, swiss, novelist]"
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known...","baroness fabienne-claire nothomb, better known...",baroness fabienneclaire nothomb better known b...,baroness fabienneclaire nothomb better known p...,"[baroness, fabienneclaire, nothomb, better, kn..."
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer...","harlan coben (born january 4, 1962) is an amer...",harlan coben born january 4 1962 is an america...,harlan coben born january 4 1962 american writ...,"[harlan, coben, born, january, 4, 1962, americ..."
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo...","dame agatha mary clarissa christie, lady mallo...",dame agatha mary clarissa christie lady mallow...,dame agatha mary clarissa christie lady mallow...,"[dame, agatha, mary, clarissa, christie, lady,..."
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...,david foenkinos (born 28 october 1974) is a fr...,david foenkinos born 28 october 1974 is a fren...,david foenkinos born 28 october 1974 french au...,"[david, foenkinos, born, 28, october, 1974, fr..."
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier born 21 april 1957 is a frenc...,hervé le tellier born 21 april 1957 french wri...,"[hervé, le, tellier, born, 21, april, 1957, fr..."
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ...","arch colson chipp whitehead (born november 6, ...",arch colson chipp whitehead born november 6 19...,arch colson chipp whitehead born november 6 19...,"[arch, colson, chipp, whitehead, born, novembe..."
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi born 1965042929 april 1965 in lou...,michel bussi born 1965042929 april 1965 louvie...,"[michel, bussi, born, 1965042929, april, 1965,..."
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso french pronunciation ɡijom mys...,guillaume musso french pronunciation ɡijom mys...,"[guillaume, musso, french, pronunciation, ɡijo..."
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett american writer based los angeles...,"[brit, bennett, american, writer, based, los, ..."
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...,bernard werber (born 1961 in toulouse) is a fr...,bernard werber born 1961 in toulouse is a fren...,bernard werber born 1961 toulouse french scien...,"[bernard, werber, born, 1961, toulouse, french..."
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ...","laurent mauvignier (born in 1967, tours) is a ...",laurent mauvignier born in 1967 tours is a fre...,laurent mauvignier born 1967 tours french writer,"[laurent, mauvignier, born, 1967, tours, frenc..."
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...,lola lafon (born 1974) is a french writer and ...,lola lafon born 1974 is a french writer and mu...,lola lafon born 1974 french writer musician bo...,"[lola, lafon, born, 1974, french, writer, musi..."
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 ...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 n...,"[stefan, zweig, german, ˈʃtɛfan, tsvaɪk, liste..."
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...,laure adler (née laure clauzet; born 11 march ...,laure adler née laure clauzet born 11 march 19...,laure adler née laure clauzet born 11 march 19...,"[laure, adler, née, laure, clauzet, born, 11, ..."
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...,alice zeniter (born 1986) is a french novelist...,alice zeniter born 1986 is a french novelist t...,alice zeniter born 1986 french novelist transl...,"[alice, zeniter, born, 1986, french, novelist,..."
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ...","erri de luca (born 20 may 1950, naples) is an ...",erri de luca born 20 may 1950 naples is an ita...,erri de luca born 20 may 1950 naples italian n...,"[erri, de, luca, born, 20, may, 1950, naples, ..."
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:...","émile édouard charles antoine zola (, also us:...",émile édouard charles antoine zola also us f...,émile édouard charles antoine zola also us fre...,"[émile, édouard, charles, antoine, zola, also,..."
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...,carole martinez (10 november 1966 in créhange)...,carole martinez 10 november 1966 in créhange i...,carole martinez 10 november 1966 créhange fren...,"[carole, martinez, 10, november, 1966, créhang..."
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...,marie-hélène lafon (born 1962) is a french edu...,mariehélène lafon born 1962 is a french educat...,mariehélène lafon born 1962 french educator aw...,"[mariehélène, lafon, born, 1962, french, educa..."

### Stemming

In [16]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("french", ignore_stopwords=True)

**Tips :** 
- Use `withoutStopwords` column
- If you want to transform a list of string into a string, you can use `' '.join([])`

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction,withoutStopwords,tokenized,stemming
0,Marc Levy (born 16 October 1961) is a French n...,10,54,6,4,marc levy (born 16 october 1961) is a french n...,marc levy (born 16 october 1961) is a french n...,marc levy born 16 october 1961 is a french nov...,marc levy born 16 october 1961 french novelist,"[marc, levy, born, 16, october, 1961, french, ...",marc levy born 16 octob 1961 french novelist
1,Emmanuel Carrère (born 9 December 1957) is a F...,14,91,5,4,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère (born 9 december 1957) is a f...,emmanuel carrère born 9 december 1957 is a fre...,emmanuel carrère born 9 december 1957 french a...,"[emmanuel, carrère, born, 9, december, 1957, f...",emmanuel carrer born 9 decemb 1957 french auth...
2,Franck Thilliez (born 15 October 1973 in Annec...,35,191,6,9,franck thilliez (born 15 october 1973 in annec...,franck thilliez (born 15 october 1973 in annec...,franck thilliez born 15 october 1973 in annecy...,franck thilliez born 15 october 1973 annecy fr...,"[franck, thilliez, born, 15, october, 1973, an...",franck thill born 15 octob 1973 annecy french ...
3,"Kenneth Martin Follett, (born 5 June 1949) is...",85,476,9,33,"kenneth martin follett, (born 5 june 1949) is...","kenneth martin follett, (born 5 june 1949) is...",kenneth martin follett born 5 june 1949 is a ...,kenneth martin follett born 5 june 1949 welsh ...,"[kenneth, martin, follett, born, 5, june, 1949...",kenneth martin follet born 5 jun 1949 welsh au...
4,"Stephen Edwin King (born September 21, 1947) i...",190,1193,30,54,"stephen edwin king (born september 21, 1947) i...","stephen edwin king (born september 21, 1947) i...",stephen edwin king born september 21 1947 is a...,stephen edwin king born september 21 1947 amer...,"[stephen, edwin, king, born, september, 21, 19...",stephen edwin king born septemb 21 1947 americ...
5,Pierre Lemaitre (born 19 April 1951 in Paris) ...,110,688,22,42,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre (born 19 april 1951 in paris) ...,pierre lemaitre born 19 april 1951 in paris is...,pierre lemaitre born 19 april 1951 paris prix ...,"[pierre, lemaitre, born, 19, april, 1951, pari...",pierr lemaitr born 19 april 1951 paris prix go...
6,Joël Dicker (born 1985) is a Swiss novelist.,8,44,4,3,joël dicker (born 1985) is a swiss novelist.,joël dicker (born 1985) is a swiss novelist.,joël dicker born 1985 is a swiss novelist,joël dicker born 1985 swiss novelist,"[joël, dicker, born, 1985, swiss, novelist]",joël dick born 1985 swiss novelist
7,"Baroness Fabienne-Claire Nothomb, better known...",128,741,12,35,"baroness fabienne-claire nothomb, better known...","baroness fabienne-claire nothomb, better known...",baroness fabienneclaire nothomb better known b...,baroness fabienneclaire nothomb better known p...,"[baroness, fabienneclaire, nothomb, better, kn...",baroness fabienneclair nothomb bet known pen n...
8,"Harlan Coben (born January 4, 1962) is an Amer...",65,394,5,10,"harlan coben (born january 4, 1962) is an amer...","harlan coben (born january 4, 1962) is an amer...",harlan coben born january 4 1962 is an america...,harlan coben born january 4 1962 american writ...,"[harlan, coben, born, january, 4, 1962, americ...",harlan coben born january 4 1962 american writ...
9,"Dame Agatha Mary Clarissa Christie, Lady Mallo...",427,2660,77,111,"dame agatha mary clarissa christie, lady mallo...","dame agatha mary clarissa christie, lady mallo...",dame agatha mary clarissa christie lady mallow...,dame agatha mary clarissa christie lady mallow...,"[dame, agatha, mary, clarissa, christie, lady,...",dam agath mary clariss christ lady mallowan né...
10,David Foenkinos (born 28 October 1974) is a Fr...,57,331,14,17,david foenkinos (born 28 october 1974) is a fr...,david foenkinos (born 28 october 1974) is a fr...,david foenkinos born 28 october 1974 is a fren...,david foenkinos born 28 october 1974 french au...,"[david, foenkinos, born, 28, october, 1974, fr...",david foenkinos born 28 octob 1974 french auth...
11,Hervé Le Tellier (born 21 April 1957) is a Fre...,57,389,6,23,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier (born 21 april 1957) is a fre...,hervé le tellier born 21 april 1957 is a frenc...,hervé le tellier born 21 april 1957 french wri...,"[hervé, le, tellier, born, 21, april, 1957, fr...",herv le telli born 21 april 1957 french writ l...
12,"Arch Colson Chipp Whitehead (born November 6, ...",80,480,29,32,"arch colson chipp whitehead (born november 6, ...","arch colson chipp whitehead (born november 6, ...",arch colson chipp whitehead born november 6 19...,arch colson chipp whitehead born november 6 19...,"[arch, colson, chipp, whitehead, born, novembe...",arch colson chipp whitehead born novemb 6 1969...
13,Michel Bussi (born (1965-04-29)29 April 1965 i...,102,668,30,40,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi (born (1965-04-29)29 april 1965 i...,michel bussi born 1965042929 april 1965 in lou...,michel bussi born 1965042929 april 1965 louvie...,"[michel, bussi, born, 1965042929, april, 1965,...",michel buss born 1965042929 april 1965 louvi e...
14,Guillaume Musso (French pronunciation: ​[ɡijom...,14,93,5,5,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso (french pronunciation: ​[ɡijom...,guillaume musso french pronunciation ɡijom mys...,guillaume musso french pronunciation ɡijom mys...,"[guillaume, musso, french, pronunciation, ɡijo...",guillaum musso french pronunci ɡijom myso born...
15,Brit Bennett is an American writer based in Lo...,47,268,8,23,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett is an american writer based in lo...,brit bennett american writer based los angeles...,"[brit, bennett, american, writer, based, los, ...",brit bennet american writ based los angel debu...
16,Bernard Werber (born 1961 in Toulouse) is a Fr...,52,350,8,9,bernard werber (born 1961 in toulouse) is a fr...,bernard werber (born 1961 in toulouse) is a fr...,bernard werber born 1961 in toulouse is a fren...,bernard werber born 1961 toulouse french scien...,"[bernard, werber, born, 1961, toulouse, french...",bernard werb born 1961 toulous french scienc f...
17,"Laurent Mauvignier (born in 1967, Tours) is a ...",10,60,4,4,"laurent mauvignier (born in 1967, tours) is a ...","laurent mauvignier (born in 1967, tours) is a ...",laurent mauvignier born in 1967 tours is a fre...,laurent mauvignier born 1967 tours french writer,"[laurent, mauvignier, born, 1967, tours, frenc...",laurent mauvigni born 1967 tour french writ
18,Lola Lafon (born 1974) is a French writer and ...,81,468,4,30,lola lafon (born 1974) is a french writer and ...,lola lafon (born 1974) is a french writer and ...,lola lafon born 1974 is a french writer and mu...,lola lafon born 1974 french writer musician bo...,"[lola, lafon, born, 1974, french, writer, musi...",lol lafon born 1974 french writ musician born ...
19,Stefan Zweig (; German: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,318,1952,90,99,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig (; german: [ˈʃtɛ.fan t͡svaɪ̯k] (l...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 ...,stefan zweig german ˈʃtɛfan tsvaɪk listen 28 n...,"[stefan, zweig, german, ˈʃtɛfan, tsvaɪk, liste...",stefan zweig german ˈʃtɛfan tsvaɪk listen 28 n...
20,Laure Adler (née Laure Clauzet; born 11 March ...,20,125,6,9,laure adler (née laure clauzet; born 11 march ...,laure adler (née laure clauzet; born 11 march ...,laure adler née laure clauzet born 11 march 19...,laure adler née laure clauzet born 11 march 19...,"[laure, adler, née, laure, clauzet, born, 11, ...",laur adler né laur clauzet born 11 march 1950 ...
21,Alice Zeniter (born 1986) is a French novelist...,87,507,10,25,alice zeniter (born 1986) is a french novelist...,alice zeniter (born 1986) is a french novelist...,alice zeniter born 1986 is a french novelist t...,alice zeniter born 1986 french novelist transl...,"[alice, zeniter, born, 1986, french, novelist,...",alic zenit born 1986 french novelist translato...
22,"Erri De Luca (born 20 May 1950, Naples) is an ...",84,479,12,22,"erri de luca (born 20 may 1950, naples) is an ...","erri de luca (born 20 may 1950, naples) is an ...",erri de luca born 20 may 1950 naples is an ita...,erri de luca born 20 may 1950 naples italian n...,"[erri, de, luca, born, 20, may, 1950, naples, ...",erri de luc born 20 may 1950 napl italian nove...
23,"Émile Édouard Charles Antoine Zola (, also US:...",94,601,19,21,"émile édouard charles antoine zola (, also us:...","émile édouard charles antoine zola (, also us:...",émile édouard charles antoine zola also us f...,émile édouard charles antoine zola also us fre...,"[émile, édouard, charles, antoine, zola, also,...",émil édouard charl antoin zol also us french e...
24,Carole Martinez (10 November 1966 in Créhange)...,12,81,6,5,carole martinez (10 november 1966 in créhange)...,carole martinez (10 november 1966 in créhange)...,carole martinez 10 november 1966 in créhange i...,carole martinez 10 november 1966 créhange fren...,"[carole, martinez, 10, november, 1966, créhang...",carol martin 10 novemb 1966 créhang french con...
25,Marie-Hélène Lafon (born 1962) is a French edu...,83,485,18,15,marie-hélène lafon (born 1962) is a french edu...,marie-hélène lafon (born 1962) is a french edu...,mariehélène lafon born 1962 is a french educat...,mariehélène lafon born 1962 french educator aw...,"[mariehélène, lafon, born, 1962, french, educa...",mariehélen lafon born 1962 french educator awa...

## Advanced text processing

### N-grams

In [18]:
from nltk.util import ngrams

**Tips :** Use `tokenized` column

0     [(marc, levy), (levy, born), (born, 16), (16, ...
1     [(emmanuel, carrère), (carrère, born), (born, ...
2     [(franck, thilliez), (thilliez, born), (born, ...
3     [(kenneth, martin), (martin, follett), (follet...
4     [(stephen, edwin), (edwin, king), (king, born)...
5     [(pierre, lemaitre), (lemaitre, born), (born, ...
6     [(joël, dicker), (dicker, born), (born, 1985),...
7     [(baroness, fabienneclaire), (fabienneclaire, ...
8     [(harlan, coben), (coben, born), (born, januar...
9     [(dame, agatha), (agatha, mary), (mary, claris...
10    [(david, foenkinos), (foenkinos, born), (born,...
11    [(hervé, le), (le, tellier), (tellier, born), ...
12    [(arch, colson), (colson, chipp), (chipp, whit...
13    [(michel, bussi), (bussi, born), (born, 196504...
14    [(guillaume, musso), (musso, french), (french,...
15    [(brit, bennett), (bennett, american), (americ...
16    [(bernard, werber), (werber, born), (born, 196...
17    [(laurent, mauvignier), (mauvignier, born), (b...
18    [(lola, lafon), (lafon, born), (born, 1974), (...
19    [(stefan, zweig), (zweig, german), (german, ˈʃ...
20    [(laure, adler), (adler, née), (née, laure), (...
21    [(alice, zeniter), (zeniter, born), (born, 198...
22    [(erri, de), (de, luca), (luca, born), (born, ...
23    [(émile, édouard), (édouard, charles), (charle...
24    [(carole, martinez), (martinez, 10), (10, nove...
25    [(mariehélène, lafon), (lafon, born), (born, 1...
Name: n-grams, dtype: object

### Term Frequency (TF)

In [20]:
tokenized_description = data.loc[4, 'tokenized']

In [21]:
tokenized_description

['stephen',
 'edwin',
 'king',
 'born',
 'september',
 '21',
 '1947',
 'american',
 'author',
 'horror',
 'supernatural',
 'fiction',
 'suspense',
 'crime',
 'sciencefiction',
 'fantasy',
 'novels',
 'books',
 'sold',
 '350',
 'million',
 'copies',
 'many',
 'adapted',
 'films',
 'television',
 'series',
 'miniseries',
 'comic',
 'books',
 'king',
 'published',
 '61',
 'novels',
 'including',
 'seven',
 'pen',
 'name',
 'richard',
 'bachman',
 'five',
 'nonfiction',
 'books',
 'also',
 'written',
 'approximately',
 '200',
 'short',
 'stories',
 'published',
 'book',
 'collectionsking',
 'received',
 'bram',
 'stoker',
 'awards',
 'world',
 'fantasy',
 'awards',
 'british',
 'fantasy',
 'society',
 'awards',
 '2003',
 'national',
 'book',
 'foundation',
 'awarded',
 'medal',
 'distinguished',
 'contribution',
 'american',
 'letters',
 'also',
 'received',
 'awards',
 'contribution',
 'literature',
 'entire',
 'bibliography',
 '2004',
 'world',
 'fantasy',
 'award',
 'life',
 'achievement',
 '2007',
 'grand',
 'master',
 'award',
 'mystery',
 'writers',
 'america',
 '2015',
 'awarded',
 'national',
 'medal',
 'arts',
 'us',
 'national',
 'endowment',
 'arts',
 'contributions',
 'literature',
 'described',
 'king',
 'horror',
 'play',
 'surname',
 'reference',
 'high',
 'standing',
 'pop',
 'culture']

**Tips :** 
- Build a dictionnay `{word:count, word1:count1, ...}` 

- **/!\\** take care to not override already existing keys

{'1947': 1,
 '200': 1,
 '2003': 1,
 '2004': 1,
 '2007': 1,
 '2015': 1,
 '21': 1,
 '350': 1,
 '61': 1,
 'achievement': 1,
 'adapted': 1,
 'also': 2,
 'america': 1,
 'american': 2,
 'approximately': 1,
 'arts': 2,
 'author': 1,
 'award': 2,
 'awarded': 2,
 'awards': 4,
 'bachman': 1,
 'bibliography': 1,
 'book': 2,
 'books': 3,
 'born': 1,
 'bram': 1,
 'british': 1,
 'collectionsking': 1,
 'comic': 1,
 'contribution': 2,
 'contributions': 1,
 'copies': 1,
 'crime': 1,
 'culture': 1,
 'described': 1,
 'distinguished': 1,
 'edwin': 1,
 'endowment': 1,
 'entire': 1,
 'fantasy': 4,
 'fiction': 1,
 'films': 1,
 'five': 1,
 'foundation': 1,
 'grand': 1,
 'high': 1,
 'horror': 2,
 'including': 1,
 'king': 3,
 'letters': 1,
 'life': 1,
 'literature': 2,
 'many': 1,
 'master': 1,
 'medal': 2,
 'million': 1,
 'miniseries': 1,
 'mystery': 1,
 'name': 1,
 'national': 3,
 'nonfiction': 1,
 'novels': 2,
 'pen': 1,
 'play': 1,
 'pop': 1,
 'published': 2,
 'received': 2,
 'reference': 1,
 'richard': 1,
 'sciencefiction': 1,
 'september': 1,
 'series': 1,
 'seven': 1,
 'short': 1,
 'society': 1,
 'sold': 1,
 'standing': 1,
 'stephen': 1,
 'stoker': 1,
 'stories': 1,
 'supernatural': 1,
 'surname': 1,
 'suspense': 1,
 'television': 1,
 'us': 1,
 'world': 2,
 'writers': 1,
 'written': 1}

In [23]:
document_frequency_df = pd.DataFrame.from_dict(
    words, orient='index', columns=['wordCount']).reset_index()
document_frequency_df.columns = ['word', 'wordCount']
document_frequency_df

              word  wordCount
0          stephen          1
1            edwin          1
2             king          3
3             born          1
4        september          1
5               21          1
6             1947          1
7         american          2
8           author          1
9           horror          2
10    supernatural          1
11         fiction          1
12        suspense          1
13           crime          1
14  sciencefiction          1
15         fantasy          4
16          novels          2
17           books          3
18            sold          1
19             350          1
20         million          1
21          copies          1
22            many          1
23         adapted          1
24           films          1
25      television          1
26          series          1
27      miniseries          1
28           comic          1
29       published          2
..             ...        ...
58           medal          2
59   distinguished          1
60    contribution          2
61         letters          1
62      literature          2
63          entire          1
64    bibliography          1
65            2004          1
66           award          2
67            life          1
68     achievement          1
69            2007          1
70           grand          1
71          master          1
72         mystery          1
73         writers          1
74         america          1
75            2015          1
76            arts          2
77              us          1
78       endowment          1
79   contributions          1
80       described          1
81            play          1
82         surname          1
83       reference          1
84            high          1
85        standing          1
86             pop          1
87         culture          1

[88 rows x 2 columns]

**Tips :** use `advanced_processing_df`

**Reminder :** Term Frequency is `wordCount` divided by total number of words

              word  wordCount        tf
0          stephen          1  0.008772
1            edwin          1  0.008772
2             king          3  0.026316
3             born          1  0.008772
4        september          1  0.008772
5               21          1  0.008772
6             1947          1  0.008772
7         american          2  0.017544
8           author          1  0.008772
9           horror          2  0.017544
10    supernatural          1  0.008772
11         fiction          1  0.008772
12        suspense          1  0.008772
13           crime          1  0.008772
14  sciencefiction          1  0.008772
15         fantasy          4  0.035088
16          novels          2  0.017544
17           books          3  0.026316
18            sold          1  0.008772
19             350          1  0.008772
20         million          1  0.008772
21          copies          1  0.008772
22            many          1  0.008772
23         adapted          1  0.008772
24           films          1  0.008772
25      television          1  0.008772
26          series          1  0.008772
27      miniseries          1  0.008772
28           comic          1  0.008772
29       published          2  0.017544
..             ...        ...       ...
58           medal          2  0.017544
59   distinguished          1  0.008772
60    contribution          2  0.017544
61         letters          1  0.008772
62      literature          2  0.017544
63          entire          1  0.008772
64    bibliography          1  0.008772
65            2004          1  0.008772
66           award          2  0.017544
67            life          1  0.008772
68     achievement          1  0.008772
69            2007          1  0.008772
70           grand          1  0.008772
71          master          1  0.008772
72         mystery          1  0.008772
73         writers          1  0.008772
74         america          1  0.008772
75            2015          1  0.008772
76            arts          2  0.017544
77              us          1  0.008772
78       endowment          1  0.008772
79   contributions          1  0.008772
80       described          1  0.008772
81            play          1  0.008772
82         surname          1  0.008772
83       reference          1  0.008772
84            high          1  0.008772
85        standing          1  0.008772
86             pop          1  0.008772
87         culture          1  0.008772

[88 rows x 3 columns]

### Inverse Document Frequency (IDF)

**Reminder :** IDF (**I**nverse **D**ocument **F**requency) is 1 divided by number of row in `data` that contains the word you want to calculate IDF score.

              word  wordCount        tf       idf
0          stephen          1  0.008772  1.000000
1            edwin          1  0.008772  1.000000
2             king          3  0.026316  0.333333
3             born          1  0.008772  0.047619
4        september          1  0.008772  0.333333
5               21          1  0.008772  0.500000
6             1947          1  0.008772  1.000000
7         american          2  0.017544  0.250000
8           author          1  0.008772  0.100000
9           horror          2  0.017544  1.000000
10    supernatural          1  0.008772  1.000000
11         fiction          1  0.008772  0.166667
12        suspense          1  0.008772  1.000000
13           crime          1  0.008772  0.333333
14  sciencefiction          1  0.008772  1.000000
15         fantasy          4  0.035088  1.000000
16          novels          2  0.017544  0.100000
17           books          3  0.026316  0.250000
18            sold          1  0.008772  0.333333
19             350          1  0.008772  1.000000
20         million          1  0.008772  0.333333
21          copies          1  0.008772  0.250000
22            many          1  0.008772  0.250000
23         adapted          1  0.008772  0.500000
24           films          1  0.008772  0.500000
25      television          1  0.008772  0.500000
26          series          1  0.008772  0.333333
27      miniseries          1  0.008772  1.000000
28           comic          1  0.008772  1.000000
29       published          2  0.017544  0.125000
..             ...        ...       ...       ...
58           medal          2  0.017544  1.000000
59   distinguished          1  0.008772  1.000000
60    contribution          2  0.017544  0.500000
61         letters          1  0.008772  1.000000
62      literature          2  0.017544  0.142857
63          entire          1  0.008772  1.000000
64    bibliography          1  0.008772  1.000000
65            2004          1  0.008772  1.000000
66           award          2  0.017544  0.142857
67            life          1  0.008772  0.333333
68     achievement          1  0.008772  1.000000
69            2007          1  0.008772  1.000000
70           grand          1  0.008772  0.333333
71          master          1  0.008772  0.333333
72         mystery          1  0.008772  0.333333
73         writers          1  0.008772  0.333333
74         america          1  0.008772  0.200000
75            2015          1  0.008772  0.200000
76            arts          2  0.017544  1.000000
77              us          1  0.008772  0.071429
78       endowment          1  0.008772  1.000000
79   contributions          1  0.008772  0.500000
80       described          1  0.008772  1.000000
81            play          1  0.008772  0.250000
82         surname          1  0.008772  1.000000
83       reference          1  0.008772  1.000000
84            high          1  0.008772  0.250000
85        standing          1  0.008772  1.000000
86             pop          1  0.008772  0.500000
87         culture          1  0.008772  1.000000

[88 rows x 4 columns]

### TF-IDF

**Reminder :** TF-IDF formula is ```tf * idf```

              word  wordCount        tf       idf    tf-idf
0          stephen          1  0.008772  1.000000  0.008772
1            edwin          1  0.008772  1.000000  0.008772
2             king          3  0.026316  0.333333  0.008772
3             born          1  0.008772  0.047619  0.000418
4        september          1  0.008772  0.333333  0.002924
5               21          1  0.008772  0.500000  0.004386
6             1947          1  0.008772  1.000000  0.008772
7         american          2  0.017544  0.250000  0.004386
8           author          1  0.008772  0.100000  0.000877
9           horror          2  0.017544  1.000000  0.017544
10    supernatural          1  0.008772  1.000000  0.008772
11         fiction          1  0.008772  0.166667  0.001462
12        suspense          1  0.008772  1.000000  0.008772
13           crime          1  0.008772  0.333333  0.002924
14  sciencefiction          1  0.008772  1.000000  0.008772
15         fantasy          4  0.035088  1.000000  0.035088
16          novels          2  0.017544  0.100000  0.001754
17           books          3  0.026316  0.250000  0.006579
18            sold          1  0.008772  0.333333  0.002924
19             350          1  0.008772  1.000000  0.008772
20         million          1  0.008772  0.333333  0.002924
21          copies          1  0.008772  0.250000  0.002193
22            many          1  0.008772  0.250000  0.002193
23         adapted          1  0.008772  0.500000  0.004386
24           films          1  0.008772  0.500000  0.004386
25      television          1  0.008772  0.500000  0.004386
26          series          1  0.008772  0.333333  0.002924
27      miniseries          1  0.008772  1.000000  0.008772
28           comic          1  0.008772  1.000000  0.008772
29       published          2  0.017544  0.125000  0.002193
..             ...        ...       ...       ...       ...
58           medal          2  0.017544  1.000000  0.017544
59   distinguished          1  0.008772  1.000000  0.008772
60    contribution          2  0.017544  0.500000  0.008772
61         letters          1  0.008772  1.000000  0.008772
62      literature          2  0.017544  0.142857  0.002506
63          entire          1  0.008772  1.000000  0.008772
64    bibliography          1  0.008772  1.000000  0.008772
65            2004          1  0.008772  1.000000  0.008772
66           award          2  0.017544  0.142857  0.002506
67            life          1  0.008772  0.333333  0.002924
68     achievement          1  0.008772  1.000000  0.008772
69            2007          1  0.008772  1.000000  0.008772
70           grand          1  0.008772  0.333333  0.002924
71          master          1  0.008772  0.333333  0.002924
72         mystery          1  0.008772  0.333333  0.002924
73         writers          1  0.008772  0.333333  0.002924
74         america          1  0.008772  0.200000  0.001754
75            2015          1  0.008772  0.200000  0.001754
76            arts          2  0.017544  1.000000  0.017544
77              us          1  0.008772  0.071429  0.000627
78       endowment          1  0.008772  1.000000  0.008772
79   contributions          1  0.008772  0.500000  0.004386
80       described          1  0.008772  1.000000  0.008772
81            play          1  0.008772  0.250000  0.002193
82         surname          1  0.008772  1.000000  0.008772
83       reference          1  0.008772  1.000000  0.008772
84            high          1  0.008772  0.250000  0.002193
85        standing          1  0.008772  1.000000  0.008772
86             pop          1  0.008772  0.500000  0.004386
87         culture          1  0.008772  1.000000  0.008772

[88 rows x 5 columns]

### Bag of words

In [27]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [28]:
descriptions = data['withoutStopwords'].values.tolist()

**Tips :** Use cv method to fit and transform cv on description to get countVectorizer result

,marc,levy,born,16,october,1961,french,novelist,emmanuel,carrère,...,grammaire,1987,going,teach,classical,34,publishing,soir,chien,2001
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,1,0,...,0,3,2,0,0,0,0,0,0,1
20,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,1,0,0,...,2,0,0,0,1,1,0,1,0,0
24,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0